language: c
script:
- make RELNUM=1.$TRAVIS_BUILD_NUMBER OPTFLAGS=-O2 LDFLAGS=-s
- make RELNUM=1.$TRAVIS_BUILD_NUMBER rpm
compiler: gcc
sudo: false
before_install:
- gem install fpm
addons:
  apt:
    packages:
    - rpm
deploy:
  provider: packagecloud
  repository: aliuly/localapps
  username: aliuly
  dist: el/7
  token:
    secure: NgHbUKMAC/DpBH1mxPI73FOUa6mKcch/PtO8HoFmpgmT26OMEYRmbceJWtPlrpHZwlEh9NGgv3FkU18oyfaYmtQH/T5jBzBGxslUSO9YiURI6nFcHpKkBH+hvR9MskdoI0ZGpH1HuJlCBL27mbYS4dbP/g/qqceoRbX1sBidQGM9AB6OOcENj38GwL3yWLjbxuLztKUtiteEbJpdWVWjG3iW9JcpXDmQpU1wpx7fZjIyJ+xvicL98GUGePTw9Rw+4Tdw1N7AsQKIbOu/qBOUoNcuKbYaNKxph4NYtZtaa9s5tHkeLvFcG+k04FUZnK3rj2peeXZjyXip4Lfk+InUWiFaI3j9TSoift+EKIy53HP+2+8UXodteACQzq3n9+FVMIXtWQNgQz70yKTUnjJA7XzrQCIDJnB3JAixh3kwepmI6qZK4bb0rQa1J4j1ykNEsNW4jP7ARNsKKSfj5ap1K/6NZOn1IdR+KGLtKv3StJTkqKyuBNXZOIKcoK4pKZyHY5ktVZ1Rw3DTePCh90wuye/UM148F1kgTs3oM6zygWagkj/qI3IqTAS9TnB7dkehCEdlmq0cRDDmLJRsPvWD1lytd7ilhXPl0cfTrsJv/YbfzXaBIPapuacLfXsmKwMW6ti+PQo8jsa31kxy9EdD+53i93Qvp+baN3kL/dmHMXU=
