language: c
script:
 - make RELNUM=1.$TRAVIS_BUILD_NUMBER OPTFLAGS=-O2 LDFLAGS=-s
 - make RELNUM=1.$TRAVIS_BUILD_NUMBER rpm
 - make RELNUM=1.$TRAVIS_BUILD_NUMBER push
 - package_cloud push aliuly/localapps/el/7 *.rpm
compiler: gcc
sudo: false
before_install:
 - gem install fpm
 - gem install package_cloud
env:
 - secure: "zZVG+4sMAKuOPgQ8PZRzxryM0oO+Xn1DKt3wfsZwJcL0aOeDA6RMB5sSAIs2uxQWl8LgpKzpKPlsIWktSu/BUntHxtTzDxYrTpN1u64YvHaRlVH64KfbP+TxnB1yEsxqnPaBanwMl/KVsElbDvLdXfdqr7jygUTNuP/0FxIUzixmk0la4V1hUvDQ+Iog6qY7u5DfNKg3ZbnrWEALAH/EN9324+sZ5nFAaqkaDtP/Mzh20SLYZS8F5hbosTCXl2lGsZqHQBnHo322IWHBCsBkRyTGGlApETQZ5xkM6TlhimH9J+dVNCRg2Xi/cEiqEqgkcM0NMSnuw+IWaHLASJy1eATzBkakreotzAIslJfexsO3fgdEguAJSTPulmWADRZUDO1DzjBRWJ7tegBj4z0Yk8rnXRqqC2IuWSFv+4nnnySG+WdUnzmey2zvtnT+YVHmQvPSm3lTBsv8NLJDNXIAkS5bQ0ulQdFUlEW37DVnL/MXlN5CRXA9uc07ufkBvuS43+/DrCqXEhjAYXU1o4o9iAVJEqCESBJW//1vNEs+UwH66NHRIRPTpbbU+SVa9Msch46wXSqkOOP5xYDJdTloyHfmeJxbfV+03IvJHY+ZlxvRXd3Y4cx4/GbOI95Gw8m8Oa31NLwIWpVD5343JLO1doh1GpYSIzhe2mHVXV7EKus="

addons:
  apt:
    packages:
    - rpm
